version: "2"

services:
  mesh:
    build: .
    depends_on:
    - nginx
    - rabbitmq
    volumes:
    - ./:/usr/local/src/mesh

  nginx:
    image: nginx:1.11.5-alpine
    tmpfs:
    - /var/log/nginx
    volumes:
    - ./nginx:/etc/nginx/conf.d

  rabbitmq:
    image: rabbitmq:3.7-management
    hostname: rabbitmq
    ports:
    - "15672:15672"
    tmpfs:
    - /var/lib/rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: cookie
